# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hasilSearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog, QApplication, QMainWindow, QMessageBox
from PyQt5.uic import loadUi
from showDetailEvent import Ui_DetailEventWindow


class Ui_searchWindow(QMainWindow):
    widget = []
    arrofEvent = []
    numofEvent = 0
    member_id = 0

    def __init__(self, widget, arrofEvent, member_id, parent=None):
        super().__init__()
        self.widget = widget
        self.widget.addWidget(self)
        self.arrofEvent = arrofEvent
        self.numofEvent = len(arrofEvent)
        self.member_id = member_id
        # self.widget.setCurrentIndex(self.widget.currentIndex() + 1)
        loadUi("hasilSearch.ui", self)
        self.setupUi(self)
        print("Num of Event: " , self.numofEvent)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 732)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.addButton(self.arrofEvent)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 70, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton.clicked.connect(self.back)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Back"))
        self.label.setText(_translate("MainWindow", "Hasil Search"))

    def addButton(self, arrofEvent) : 
        _translate = QtCore.QCoreApplication.translate
        for i in range(len(arrofEvent)) : 
            if (i == 0) :
                self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton1.setGeometry(QtCore.QRect(50, 160, 161, 181))
                self.pushButton1.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton1.clicked.connect(lambda: self.gotoDetail(arrofEvent[0][1]))
                self.label1 = QtWidgets.QLabel(self.centralwidget)
                self.label1.setGeometry(QtCore.QRect(50, 350, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label1.setFont(font)
                self.label1.setObjectName("label1")
                self.label1.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 1) : 
                self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton2.setGeometry(QtCore.QRect(260, 160, 161, 181))
                self.pushButton2.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton2.clicked.connect(lambda: self.gotoDetail(arrofEvent[1][1]))
                self.label2 = QtWidgets.QLabel(self.centralwidget)
                self.label2.setGeometry(QtCore.QRect(260, 350, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label2.setFont(font)
                self.label2.setObjectName("label2")
                self.label2.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 2) : 
                self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton3.setGeometry(QtCore.QRect(470, 160, 161, 181))
                self.pushButton3.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton3.clicked.connect(lambda: self.gotoDetail(arrofEvent[2][1]))
                self.label3 = QtWidgets.QLabel(self.centralwidget)
                self.label3.setGeometry(QtCore.QRect(470, 350, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label3.setFont(font)
                self.label3.setObjectName("label3")
                self.label3.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 3) : 
                self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton4.setGeometry(QtCore.QRect(680, 160, 161, 181))
                self.pushButton4.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton4.clicked.connect(lambda: self.gotoDetail(arrofEvent[3][1]))
                self.label4 = QtWidgets.QLabel(self.centralwidget)
                self.label4.setGeometry(QtCore.QRect(680, 350, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label4.setFont(font)
                self.label4.setObjectName("label1")
                self.label4.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 4) :
                self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton5.setGeometry(QtCore.QRect(50, 420, 161, 181))
                self.pushButton5.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton5.clicked.connect(lambda: self.gotoDetail(arrofEvent[4][1]))
                self.label5 = QtWidgets.QLabel(self.centralwidget)
                self.label5.setGeometry(QtCore.QRect(50, 610, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label5.setFont(font)
                self.label5.setObjectName("label5")
                self.label5.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 5) : 
                self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton6.setGeometry(QtCore.QRect(260, 420, 161, 181))
                self.pushButton6.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton6.clicked.connect(lambda: self.gotoDetail(arrofEvent[5][1]))
                self.label6 = QtWidgets.QLabel(self.centralwidget)
                self.label6.setGeometry(QtCore.QRect(260, 610, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label6.setFont(font)
                self.label6.setObjectName("label6")
                self.label6.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 6) :
                self.pushButton7 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton7.setGeometry(QtCore.QRect(470, 420, 161, 181))
                self.pushButton7.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton7.clicked.connect(lambda: self.gotoDetail(arrofEvent[6][1]))
                self.label7 = QtWidgets.QLabel(self.centralwidget)
                self.label7.setGeometry(QtCore.QRect(470, 610, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label7.setFont(font)
                self.label7.setObjectName("label7")
                self.label7.setText(_translate("MainWindow", arrofEvent[i][0]))
            elif (i == 7) : 
                self.pushButton8 = QtWidgets.QPushButton(self.centralwidget)
                self.pushButton8.setGeometry(QtCore.QRect(680, 160, 161, 181))
                self.pushButton8.setStyleSheet("border-image:url(images/tickets.png)")
                self.pushButton8.clicked.connect(lambda: self.gotoDetail(arrofEvent[7][1]))
                self.label8 = QtWidgets.QLabel(self.centralwidget)
                self.label8.setGeometry(QtCore.QRect(680, 610, 161, 181))
                font = QtGui.QFont()
                font.setPointSize(11)
                self.label8.setFont(font)
                self.label8.setObjectName("label5")
                self.label8.setText(_translate("MainWindow", arrofEvent[i][0]))

    def back(self):
        self.widget.removeWidget(self)
        #self.widget.setCurrentIndex(self.widget.currentIndex()-1)

    def gotoDetail(self, id):
        showDetailEvent = Ui_DetailEventWindow(self.widget, id, self.member_id)
        self.widget.addWidget(showDetailEvent)
        self.widget.setCurrentIndex(self.widget.currentIndex() + 1)
    
        
        
        

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
